<?php
/**
 * @file staff_profile.module
 * Contains staff_profile.module
 */

/**
 * Implements hook_cron()
 */
 function staff_profile_cron() {
   //Run once per day, currently best option unless installing ultimate cron module
   if (\Drupal::config('staff_profile.settings')->get('staff_profile_lastCron') < date('Ymd')) {
     watchdog('staff_profile', 'Starting staff directory update');
     staff_profile_updater();
   }
 }

/**
 * Checks server and current staff directory for changes
 */
function staff_profile_updater() {
  \Drupal\Core\Database\Database::setActiveConnection('STAFF_DB');//TODO Add this database to settings.php
  $db = \Drupal\Core\Database\Database::getConnection();
  $data = $db->select('SELECT email FROM staff');
  $db_netids = $data->fetchAll();
  \Drupal\Core\Database\Database::setActiveConnection();
  $local_netids = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['db_tracked' => 0]);
  // Mark all unchecked netids as checked if they show up
  if ($db_netids) {
    foreach ($local_netids as $netid) {
      foreach ($db_netids as $searchid) {
        if ($netid == $searchid) {
          $netid['db_tracked'] = 1;
          $netid->save();
        }
      }
    }
  } else {
    watchdog('staff_profile', "Failed to Connect to Remote Database");
  }

  //Go through tracked ids and look if they are missing
  //TODO find a way to mark it to be hidden rather than mark to remain visible
  $local_netids = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['db_tracked' => 1]);
  if ($db_netids) {
    foreach ($local_netids as $netid) {
      foreach ($db_netids as $searchid) {
        if ($netid == $searchid) {
          //Mark profile not to be hidden
        }
      }
      //Hide $netid if it is not marked to remain visible
    }
  }
  $local_managed_netids = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['db_tracked' => 1]);





  \Drupal::configFactory()->getEditable('staff_profile.settings')
    ->set('staff_profile_lastCron', date('Ymd'))
    ->save();
  watchdog('staff_profile', 'Finished staff directory update');
}
