<?php

/*
 * Implements hook_preprocess_node()
 */
function staff_profile_preprocess_node(&$variables) {
  $node = $variables['node'];
  //check content type
  if ($node->getType() == 'staff_profile') {
    $variables['#attached']['library'][] = 'staff_profile/staff_profile'; 
  }
}

/**
 * Implements hook_form_alter().
 */
function staff_profile_form_node_form_alter(&$form, &$form_state, $form_id) {
  /* @var Drupal\Core\Entity\FieldableEntityInterface $node */
  $node = $form_state->getFormObject()->getEntity();

  if ($node->getType() == 'staff_profile') {
   /* var_dump($node);*/
    $form['#attached']['library'][] = 'staff_profile/staff_profile_edit';
  }
}
