<?php

use \Drupal\node\Entity\Node;
use \Drupal\user\Entity\User;
use \Drupal\Component\Utility\Random;
use \Drupal\encrypt\Entity\EncryptionProfile;

/**
 * Implements hook_rebuild()
 */
function staff_profile_mastersync_rebuild() {
  staff_profile_mastersync_profile_from_database();
}

function staff_profile_mastersync_profile_from_database () {
  // Get all Staff Profile nodes
  $nids = \Drupal::entityQuery('node')->condition('type','staff_profile')->execute();
  $nodes =  Node::loadMultiple($nids);

  $mastersync_config = \Drupal::config('staff_profile_mastersync.settings');

  if (empty($mastersync_config->get('db_password'))) {
    \Drupal::logger('staff_profile_mastersync')->warning('Configuration not found');
    return;
  }

  $db_database = $mastersync_config->get('db_database');
  $db_username = $mastersync_config->get('db_username');
  $db_server = $mastersync_config->get('db_address');

  $encrypt_profile = EncryptionProfile::load($mastersync_config->get('sync_encrypt_profile'));
  $db_password = \Drupal::service('encryption')->decrypt( $mastersync_config->get('db_password'), $encrypt_profile);


  // Query the staff profiles from the database
  $dbhandle = sqlsrv_connect($db_server, array('Database' => $db_database, 'UID' => $db_username, 'PWD' => $db_password));
  if ($dbhandle === FALSE) {
    \Drupal::logger('staff_profile_mastersync')->error('Couldn\'t connect to SQL Server on ' . $db_server);
    return;
  }
  $results = sqlsrv_query($dbhandle, 'dbo.Staff_GetFullDirectory');
  if ($results === false) {
    \Drupal::logger('staff_profile_mastersync')->error(print_r(sqlsrv_errors(), true));
    return;
  }
//\Drupal::logger('staff_profile_mastersync')->info('Count: ' . sqlsrv_num_rows($results));

  // Unpublish all published nodes from the Staff Directory Database
  foreach ($nodes as $node) {
    if ($node->isPublished() && !empty($node->field_staffid->value)) {
      $node->setUnpublished()->save();
    }
  }


$count = 0;
  while ($profile = sqlsrv_fetch_object($results)) {

    $mynode = '';
    foreach ($nodes as $node) {
      if (strtolower($node->field_email->value) == strtolower($profile->email)) {
        $mynode = $node;
        break;
      }
    }

    // Don't let the Job Title start with, or end with ' - '
    $jobtitle = $profile->JobTitle;
    if (substr($jobtitle, 0, 3) === ' - ') {
      $jobtitle = '';
    } elseif (substr($jobtitle,  -3) === ' - ') {
      $jobtitle = substr($jobtitle, 0, strlen($jobtitle)  - 3);
    }

    // Need to create a node
    if (empty($mynode)) {
      $mynode = Node::create(array('type' => 'staff_profile', 'title' => $profile->LastName . ', ' . $profile->FirstName));
      $mynode->field_email->value = $profile->email;
      $mynode->field_netid->value = str_replace('@iastate.edu', '', strtolower($profile->email));
      $mynode->field_preferred_name->value = $profile->FirstName;
      $mynode->field_preferred_phone->value = $profile->Phone;
      $mynode->field_working_title = $jobtitle;

      // Set the owner of the new node, will probably need to create the user
      $users =\Drupal::entityTypeManager()->getStorage('user')->loadByProperties(array('name' => $mynode->field_netid->value));
      $owner = reset($users);
      if (!$owner) {
        $owner = User::create(array('name' => $mynode->field_netid, 'email' => $profile->email->value, 'pass' => Random::string(40)));
        $owner->activate()->save();
      }
      $mynode->setOwner($owner);
    }

    $mynode->field_staffid->value = $profile->StaffID;
    $mynode->field_first_name->value = $profile->FirstName;
    $mynode->field_last_name->value = $profile->LastName;
    $mynode->field_addr = array(
      'country_code' => 'US',
      'address_line1' => $profile->Address1,
      'address_line2' => $profile->Address2,
      'locality' => $profile->City,
      'administrative_area' => $profile->State,
      'postal_code' => $profile->Zip,
    );
    $mynode->field_departmentid->value = $profile->DepartmentID;
    $mynode->field_job_title->value = $jobtitle;
    $mynode->field_phone->value = $profile->Phone;
    $mynode->field_fax->value = $profile->Fax;

    $taxonomy = taxonomy_term_load_multiple_by_name($profile->CountyName, 'counties_in_iowa');
    $base_county = (!empty($taxonomy) ? array_keys($taxonomy)[0] : 0);
    $mynode->field_base_county = [['target_id' => $base_county]];

    $mynode->field_college = [['value' => $profile->CollegeName]];
    $mynode->field_location = [['value' => $profile->Location]];

    $mynode->field_region->value = (!empty($profile->ExtensionArea) && (intval($profile->ExtensionArea) > 0)) ? $profile->ExtensionArea : '';

    $mynode->field_counties_served = [array()];
    $temp_array = explode(', ', $profile->CountiesServed);
    foreach ($temp_array as $index => $temp_term) {
      $taxon = taxonomy_term_load_multiple_by_name($temp_term, 'counties_in_iowa');
      if (!empty($taxon) && array_keys($taxon)[0] > 0) {
        $mynode->field_counties_served[] = ['target_id' => array_keys($taxon)[0]];
      }
    }

    $mynode->field_program_areas = [array()];
    $temp_array = explode(', ', $profile->ProgramAreas);
    foreach ($temp_array as $index => $temp_term) {
      $taxon = taxonomy_term_load_multiple_by_name($temp_term, 'program_areas');
      if (!empty($taxon) && array_keys($taxon)[0] > 0) {
        $mynode->field_program_areas[] = ['target_id' => array_keys($taxon)[0]];
      }
    }

    $mynode->setPublished();
    $mynode->save();

    $count++;
  }

  sqlsrv_close($dbhandle);
  \Drupal::logger('staff_profile_mastersync')->info('Staff from Staff Directory Database: ' . $count);
}

/*
 * Implements hook_preprocess_views_view()
 */
function staff_profile_preprocess_views_view(&$variables) {
  $variables['#cache']['contexts'][] = 'route';
  if ($variables['view_array']['#name'] == 'staff_directory') {
    $variables['#attached']['library'][] = 'staff_profile_mastersync/staff_directory';
  }
}
